from gbe.views import (
    ActChangeStateView,
    ActTechWizardView,
    AdminProfileView,
    ArticleCreate,
    ArticleDelete,
    ArticleDetail,
    ArticleDetailRestricted,
    ArticleList,
    ArticleManageList,
    ArticleUpdate,
    BiosTeachersView,
    BusinessCreate,
    BusinessUpdate,
    ClassChangeStateView,
    ClassLabelAutocomplete,
    CloneBidView,
    CoordinateActView,
    CostumeChangeStateView,
    DeletePerformerView,
    DeleteProfileView,
    EditEmailView,
    EditProfileView,
    FashionFaireView,
    HandleUserContactEmailView,
    LandingPageView,
    MakeActView,
    MakeClassView,
    MakeCostumeView,
    MakeVendorView,
    MergeProfileData,
    MergeProfileExtra,
    MergeProfileSelect,
    PerformerUpdate,
    PersonaCreate,
    PersonaUpdate,
    RegisterView,
    ReviewActListView,
    FlexibleReviewBidView,
    ReviewClassView,
    ReviewClassListView,
    ReviewCostumeView,
    ReviewCostumeListView,
    ReviewProfilesView,
    ReviewTroupesView,
    ReviewVendorView,
    ReviewVendorListView,
    ReviewVolunteerList,
    VendorChangeStateView,
    ViewActView,
    ViewClassView,
    ViewCostumeView,
    ViewBioView,
    ViewVendorView,
    VolunteerEvalCreate,
    VolunteerEvalDelete,
    VolunteerEvalUpdate,
    CoordinatorPerformerAutocomplete,
    LimitedBusinessAutocomplete,
    LimitedPerformerAutocomplete,
    LimitedPersonaAutocomplete,
    PersonaAutocomplete,
    ProfileAutocomplete,
)
from django.urls import re_path

# NOTE: in general, url patterns should end with '/?$'. This
# means "match the preceding pattern, plus an optional final '?',
# and no other characters following. So '^foo/?$' matches on
# "foo" or "foo/", but not on "foo/bar" or "foo!".
# Which is what we usually want.
app_name = "gbe"

urlpatterns = [
    #  landing page
    re_path(r'^gbe/?', LandingPageView.as_view(), name='home'),

    #  articles
    re_path(r'^news/view/(?P<slug>[-\w\d]+)',
            ArticleDetail.as_view(),
            name='news_item'),
    re_path(r'^news/priv_view/(?P<pk>.*)/$',
            ArticleDetailRestricted.as_view(),
            name='news_special'),
    re_path(r'^news/add/$', ArticleCreate.as_view(), name='news-add'),
    re_path(r'^news/delete/(?P<pk>.*)/$',
            ArticleDelete.as_view(),
            name='news-delete'),
    re_path(r'^news/update/(?P<pk>.*)/$',
            ArticleUpdate.as_view(),
            name='news-update'),
    re_path(r'^news/list/?', ArticleList.as_view(), name='news_list'),
    re_path(r'^news/manage/?',
            ArticleManageList.as_view(),
            name='news_manage'),

    # autocompletes
    re_path(r'^profile-autocomplete/$',
            ProfileAutocomplete.as_view(),
            name='profile-autocomplete'),
    re_path(
        r'^limited-business-autocomplete/$',
        LimitedBusinessAutocomplete.as_view(),
        name='limited-business-autocomplete'),
    re_path(
        r'^limited-performer-autocomplete/$',
        LimitedPerformerAutocomplete.as_view(),
        name='limited-performer-autocomplete'),
    re_path(
        r'^limited-persona-autocomplete/$',
        LimitedPersonaAutocomplete.as_view(),
        name='limited-persona-autocomplete'),
    re_path(
        r'^coordinator-performer-autocomplete/$',
        CoordinatorPerformerAutocomplete.as_view(),
        name='coordinator-performer-autocomplete'),
    re_path(
        r'^persona-autocomplete/$',
        PersonaAutocomplete.as_view(),
        name='persona-autocomplete'),
    re_path(r'^classlabel-autocomplete/$',
            ClassLabelAutocomplete.as_view(create_field='text'),
            name='classlabel-autocomplete'),

    #  bios
    re_path(r'^bios/teachers/?$',
            BiosTeachersView,
            name='bios_teacher'),

    #  acts
    re_path(r'^act/create/?$',
            MakeActView.as_view(),
            name='act_create'),
    re_path(r'^act/edit/(?P<bid_id>\d+)/?$',
            MakeActView.as_view(),
            name='act_edit'),
    re_path(r'^act/view/(?P<bid_id>\d+)/?$',
            ViewActView.as_view(),
            name='act_view'),
    re_path(r'^act/review/(?P<object_id>\d+)/?$',
            FlexibleReviewBidView.as_view(),
            name='act_review'),
    re_path(r'^act/review/?$',
            ReviewActListView.as_view(),
            name='act_review'),
    re_path(r'^act/reviewlist/?$',
            ReviewActListView.as_view(),
            name='act_review_list'),
    re_path(r'^act/changestate/(?P<object_id>\d+)/?$',
            ActChangeStateView.as_view(),
            name='act_changestate'),
    re_path(r'^act/coordinate/?$',
            CoordinateActView.as_view(),
            name='act_coord_create'),

    #  act tech info - delete act_techinfo_edit after GBE 2020
    re_path(r'^acttechinfo/edit/(\d+)/?$',
            ActTechWizardView.as_view(),
            name='act_techinfo_edit'),
    re_path(r'^acttechinfo/wizard/(?P<act_id>\d+)/?$',
            ActTechWizardView.as_view(),
            name='act_tech_wizard'),

    #  classes
    re_path(r'^class/create/?$',
            MakeClassView.as_view(),
            name='class_create'),
    re_path(r'class/edit/(?P<bid_id>\d+)/?$',
            MakeClassView.as_view(),
            name='class_edit'),
    re_path(r'^class/view/(?P<bid_id>\d+)/?$',
            ViewClassView.as_view(),
            name='class_view'),
    re_path(r'^class/review/(?P<object_id>\d+)/?$',
            ReviewClassView.as_view(),
            name='class_review'),
    re_path(r'^class/review/?$',
            ReviewClassListView.as_view(),
            name='class_review'),
    re_path(r'^class/reviewlist/?$',
            ReviewClassListView.as_view(),
            name='class_review_list'),
    re_path(r'^class/changestate/(?P<object_id>\d+)/?$',
            ClassChangeStateView.as_view(),
            name='class_changestate'),

    #  personae & businesses
    re_path(r'^bio/view/(\d+)/?$',
            ViewBioView, name='bio_view'),
    re_path(r'^persona/add/$',
            PersonaCreate.as_view(),
            name='persona-add'),
    re_path(r'^persona/(?P<pk>.*)/$',
            PersonaUpdate.as_view(),
            name='persona-update'),
    re_path(r'^performer/delete/(?P<pk>.*)/$',
            DeletePerformerView.as_view(),
            name='performer-delete'),
    re_path(r'^performer/(?P<pk>.*)/$',
            PerformerUpdate.as_view(),
            name='performer-update'),
    re_path(r'^business/add/$', BusinessCreate.as_view(), name='business-add'),
    re_path(r'^business/(?P<pk>.*)/$',
            BusinessUpdate.as_view(),
            name='business-update'),

    #  vendors
    re_path(r'^vendor/create/?$',
            MakeVendorView.as_view(),
            name='vendor_create'),
    re_path(r'^vendor/edit/(?P<bid_id>\d+)/?$',
            MakeVendorView.as_view(),
            name='vendor_edit'),
    re_path(r'^vendor/view/(?P<bid_id>\d+)/?$',
            ViewVendorView.as_view(),
            name='vendor_view'),
    re_path(r'^vendor/review/(?P<object_id>\d+)/?$',
            ReviewVendorView.as_view(),
            name='vendor_review'),
    re_path(r'^vendor/review/?$',
            ReviewVendorListView.as_view(),
            name='vendor_review'),
    re_path(r'^vendor/reviewlist/?$',
            ReviewVendorListView.as_view(),
            name='vendor_review_list'),
    re_path(r'^vendor/changestate/(?P<object_id>\d+)/?$',
            VendorChangeStateView.as_view(),
            name='vendor_changestate'),

    #  costumes
    re_path(r'^costume/create/?$',
            MakeCostumeView.as_view(),
            name='costume_create'),
    re_path(r'costume/edit/(?P<bid_id>\d+)/?$',
            MakeCostumeView.as_view(),
            name='costume_edit'),
    re_path(r'^costume/view/(?P<bid_id>\d+)/?$',
            ViewCostumeView.as_view(),
            name='costume_view'),
    re_path(r'^costume/review/(?P<object_id>\d+)/?$',
            ReviewCostumeView.as_view(),
            name='costume_review'),
    re_path(r'^costume/review/?$',
            ReviewCostumeListView.as_view(),
            name='costume_review'),
    re_path(r'^costume/reviewlist/?$',
            ReviewCostumeListView.as_view(),
            name='costume_review_list'),
    re_path(r'^costume/changestate/(?P<object_id>\d+)/?$',
            CostumeChangeStateView.as_view(),
            name='costume_changestate'),

    re_path(r'^clone/(?P<bid_type>\w+)/(?P<bid_id>\d+)/?$',
            CloneBidView,
            name='clone_bid'),

    #  miscellaneous URLs
    re_path(r'^fashion_faire/$',
            FashionFaireView, name='fashion_faire'),

    # volunteer review
    re_path(r'^volunteer/review/?$',
            ReviewVolunteerList.as_view(),
            name='volunteer_review'),
    re_path(r'^volunteer/review/add/(?P<slug>[-\w\d]+)/(?P<vol_id>\d+)/$',
            VolunteerEvalCreate.as_view(),
            name='volunteer-review-add'),
    re_path(r'^volunteer/review/delete/(?P<pk>\d+)/$',
            VolunteerEvalDelete.as_view(),
            name='volunteer-review-delete'),
    re_path(r'^volunteer/review/update/(?P<pk>\d+)/$',
            VolunteerEvalUpdate.as_view(),
            name='volunteer-review-update'),

    #  site utility stuff
    re_path(r'^accounts/register/?$',
            RegisterView.as_view(),
            name='register'),
    re_path(r'update_email/(?P<token>[^/]+)?$',
            EditEmailView.as_view(),
            name='email_update'),
    re_path(r'update_profile/?$',
            EditProfileView.as_view(),
            name='profile_update'),

    #  registration & user management
    re_path(r'^user_contact/?$',
            HandleUserContactEmailView,
            name='handle_user_contact_email'),
    re_path(r'^profile/manage/?$',
            ReviewProfilesView.as_view(),
            name='manage_users'),
    re_path(r'^profile/startmerge/(?P<pk>.*)/?$',
            MergeProfileSelect.as_view(),
            name='start_merge_users'),
    re_path(r'^profile/mergeprofile/(?P<pk>.*)/(?P<from_pk>.*)/?$',
            MergeProfileData.as_view(),
            name='merge_profiles'),
    re_path(r'^profile/mergebio/(?P<pk>.*)/(?P<from_pk>.*)/?$',
            MergeProfileExtra.as_view(),
            name='merge_bios'),
    re_path(r'^troupe/manage/?$',
            ReviewTroupesView.as_view(),
            name='manage_troupes'),
    re_path(r'^profile/admin/(?P<profile_id>\d+)/?$',
            AdminProfileView.as_view(),
            name='admin_profile'),
    re_path(r'^profile/delete/(\d+)/?$',
            DeleteProfileView,
            name='delete_profile'),
    re_path(r'^profile/landing_page/(?P<profile_id>\d+)/?$',
            LandingPageView.as_view(),
            name='admin_landing_page'),
]
