# Generated by Django 3.0.14 on 2021-06-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventbriteSettings',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('oauth', models.CharField(max_length=128)),
                ('organization_id', models.CharField(max_length=128)),
                ('system', models.IntegerField(
                    choices=[(0, 'local/debug'), (1, 'test/live')],
                    unique=True)),
            ],
            options={
                'verbose_name_plural': 'Eventbrite Settings',
            },
        ),
        migrations.RenameModel(
            old_name='BrownPaperEvents',
            new_name='TicketingEvents',
        ),
        migrations.RenameField(
            model_name='eventdetail',
            old_name='bpt_event',
            new_name='ticketing_event',
        ),
        migrations.RenameField(
            model_name='ticketingevents',
            old_name='bpt_event_id',
            new_name='event_id',
        ),
        migrations.RenameField(
            model_name='ticketitem',
            old_name='bpt_event',
            new_name='ticketing_event',
        ),
        migrations.AlterModelOptions(
            name='ticketingevents',
            options={'verbose_name_plural': 'Ticketing Events'},
        ),
        migrations.AlterField(
            model_name='eventbritesettings',
            name='organization_id',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
