# Generated by Django 3.0.14 on 2021-06-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_eventbritesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbritesettings',
            name='organization_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ticketingevents',
            name='event_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
