# Generated by Django 3.0.14 on 2021-06-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_eventbritesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='brownpapersettings',
            name='active_sync',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventbritesettings',
            name='active_sync',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketingevents',
            name='source',
            field=models.IntegerField(
                choices=[(0, 'Paypal'), (1, 'Brown Paper'), (2, 'Eventbrite')],
                default=1),
        ),
        migrations.AlterField(
            model_name='eventbritesettings',
            name='organization_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ticketingevents',
            name='event_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
