# Generated by Django 3.0.14 on 2021-06-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    # REALLY DO - keep this separate.  Let the migration that sets up source
    # make everything into BPT (that's the majority of the population)
    # then reset to default = Paypal (i.e., manual ticket create)
    dependencies = [
        ('ticketing', '0003_auto_20210610_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketingevents',
            name='source',
            field=models.IntegerField(choices=[
                (0, 'Paypal'),
                (1, 'Brown Paper'),
                (2, 'Eventbrite')],
                default=0),
        ),
    ]
