# Generated by Django 3.0.14 on 2021-08-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0007_auto_20210718_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='badge_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
