# Generated by Django 3.2.16 on 2022-11-18 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0010_auto_20221118_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleexclusion',
            name='event',
        ),
        migrations.RemoveField(
            model_name='ticketingevents',
            name='linked_events',
        ),
    ]
