# Generated by Django 3.2.16 on 2022-11-18 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0011_auto_20221118_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roleexclusion',
            old_name='event_2',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='ticketingevents',
            old_name='linked_events_2',
            new_name='linked_events',
        ),
    ]
