# Generated by Django 3.2.23 on 2023-12-02 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_event_peer'),
        ('ticketing', '0013_eventbritesettings_organizer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketingevents',
            name='source',
            field=models.IntegerField(choices=[(0, 'Paypal'), (1, 'Brown Paper'), (2, 'Eventbrite'), (3, 'Humanitix')], default=0),
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('ticketitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticketing.ticketitem')),
                ('linked_events', models.ManyToManyField(blank=True, to='scheduler.Event')),
            ],
            bases=('ticketing.ticketitem',),
        ),
        migrations.CreateModel(
            name='TicketPackage',
            fields=[
                ('ticketitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticketing.ticketitem')),
                ('conference_only_pass', models.BooleanField(default=False)),
                ('whole_shebang', models.BooleanField(default=False)),
                ('ticket_types', models.ManyToManyField(blank=True, to='ticketing.TicketType')),
            ],
            bases=('ticketing.ticketitem',),
        ),
    ]
