# Generated by Django 3.2.23 on 2024-01-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0015_humanitix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketpackage',
            name='conference_only_pass',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='order_notes',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='shipping_method',
        ),
        migrations.AddField(
            model_name='ticketitem',
            name='conference_only_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('paid', 'paid'), ('canceled', 'canceled')], default='paid', max_length=25),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
