# Generated by Django 3.2.23 on 2024-01-28 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filer',
         '0015_alter_file_owner_alter_file_polymorphic_ctype_and_more'),
        ('gbe', '0047_better_bid_on_off'),
        ('ticketing', '0016_transaction_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='e_sign_this',
            field=filer.fields.file.FilerFileField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='filer.file'),
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('name_signed', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conference', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    to='gbe.conference')),
                ('signed_file', filer.fields.file.FilerFileField(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    to='filer.file')),
                ('user', models.ForeignKey(
                    default=None,
                    on_delete=django.db.models.deletion.PROTECT,
                    to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
