# Generated by Django 3.2.23 on 2024-02-22 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0017_sign_this_thing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrownPaperSettings',
        ),
    ]
