# Generated by Django 4.2.11 on 2024-03-11 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0018_delete_brownpapersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibilitycondition',
            name='checklistitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='ticketing.checklistitem'),
        ),
        migrations.AlterField(
            model_name='roleexclusion',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='ticketing.eligibilitycondition'),
        ),
        migrations.AlterField(
            model_name='ticketingexclusion',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='ticketing.eligibilitycondition'),
        ),
    ]
