from django.urls import re_path
from ticketing import views
from ticketing.views import (
    BadgePrintView,
    CheckListItemList,
    CreateTransaction,
    ManageSignatures,
    SignatureList,
    SignForms,
    TicketPackageUpdate,
    TicketTypeUpdate,
)

app_name = "ticketing"

urlpatterns = [
    re_path('^ticketing/original/$',
        views.index,
        name='index'),
    re_path(r'^ticketing/ticket_items/$', views.ticket_items,
        name='ticket_items'),
    re_path(r'^ticketing/ticket_item_edit/?$', views.ticket_item_edit,
        name='ticket_item_edit'),
    re_path(r'^ticketing/ticket_item_edit/(?P<item_id>\d+)/?$',
        views.ticket_item_edit,
        name='ticket_item_edit'),
    re_path(r'^ticketing/ticket_package_update/(?P<pk>.*)/?$',
        TicketPackageUpdate.as_view(),
        name='ticket_package_update'),
    re_path(r'^ticketing/ticket_type_update/(?P<pk>.*)/?$',
        TicketTypeUpdate.as_view(),
        name='ticket_type_update'),
    re_path(r'^ticketing/ticket_event_edit/?$', views.ticket_event_edit,
        name='bptevent_edit'),
    re_path(r'^ticketing/ticket_event_edit/(?P<event_id>\d+)/?$',
        views.ticket_event_edit,
        name='bptevent_edit'),
    re_path(r'^ticketing/transactions/?$', views.transactions,
        name='transactions'),
    re_path(r'^ticketing/transaction/create/?$',
        CreateTransaction.as_view(),
        name='comp_ticket'),
    re_path(r'^sign_forms/?$', SignForms.as_view(), name='sign_forms'),
    re_path(r'^sign_forms/(?P<user_id>\d+)/?$',
        SignForms.as_view(),
        name='sign_forms'),
    re_path(r'^ticketing/checklist/?$',
        CheckListItemList.as_view(),
        name='checklistitem_list'),
    re_path(r'^ticketing/badges/?$',
        BadgePrintView.as_view(),
        name='badge_print'),
    re_path(r'^ticketing/set_ticket_to_event/(?P<pk>.*)/(?P<ticket_class>\w+)/' +
        '(?P<state>on|off)/(?P<gbe_event_id>\d+)/?$',
        views.set_ticket_to_event,
        name='set_ticket_to_event'),
    re_path(r'^ticketing/set_ticket_type_to_event/(?P<pk>.*)/' +
        '(?P<state>on|off)/(?P<gbe_event_id>\d+)/?$',
        views.set_ticket_to_event,
        name='set_ticket_type_to_event'),
    re_path(r'^signatures/view/$', SignatureList.as_view(), name='signature_list'),
    re_path(r'^signatures/manage/$',
        ManageSignatures.as_view(),
        name='manage_signatures'),
]
