# Generated by Django 3.0.12 on 2021-02-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0002_auto_20200912_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='performer',
            name='label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='performer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='performer',
            unique_together={('name', 'label')},
        ),
    ]
