# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-10 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0002_auto_20191110_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='address',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='room',
            name='conference',
            field=models.ManyToManyField(to='gbe.Conference'),
        ),
        migrations.AddField(
            model_name='room',
            name='map_link',
            field=models.URLField(blank=True),
        ),
    ]
