# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-17 15:09


from django.db import migrations, models


class Migration(migrations.Migration):
    # written at the same time as #11, no cross dependancy
    dependencies = [
        ('gbe', '0003_auto_20191111_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepreferences',
            name='send_bid_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profilepreferences',
            name='send_daily_schedule',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profilepreferences',
            name='send_role_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profilepreferences',
            name='send_schedule_change_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
