# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-29 15:25


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0004_auto_20191117_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='address',
            field=models.TextField(
                blank=True,
                help_text=b'This can include HTML, and it will be for formatting.',
                max_length=500),
        ),
        migrations.AlterField(
            model_name='room',
            name='map_embed',
            field=models.TextField(
                blank=True, 
                help_text=b'Use the embedded map instructions and this will display on event pages.  With Google, small size is recommended.',
                max_length=1000),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='description',
            field=models.TextField(max_length=3000),
        ),
    ]
