# Generated by Django 3.0.12 on 2021-02-27 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0003_auto_20210223_0834'),
        ('gbe', '0005_userstylepreview'),
    ]

    operations = [
    ]
