# Generated by Django 3.0.12 on 2021-04-27 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('gbe', '0006_merge_20210227_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('physical_address', models.TextField()),
                ('publish_physical_address', models.BooleanField(default=False)),
                ('img', filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_business', to=settings.FILER_IMAGE_MODEL)),
                ('owners', models.ManyToManyField(to='gbe.Profile')),
            ],
            options={
                'unique_together': {('name', 'website')},
            },
        ),
        migrations.AddField(
            model_name='vendor',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gbe.Business'),
        ),
    ]
