# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-23 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0006_vendor_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='techinfo',
            name='crew_instruct',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='techinfo',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='techinfo',
            name='feel_of_act',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='techinfo',
            name='follow_spot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='techinfo',
            name='introduction_text',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='techinfo',
            name='primary_color',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='techinfo',
            name='pronouns',
            field=models.CharField(default=b'she/her or he/hims', max_length=128),
        ),
        migrations.AddField(
            model_name='techinfo',
            name='prop_setup',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='techinfo',
            name='read_exact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='techinfo',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='techinfo',
            name='starting_position',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='techinfo',
            name='track_artist',
            field=models.CharField(blank=True, max_length=123),
        ),
        migrations.AddField(
            model_name='techinfo',
            name='track_title',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
