# Generated by Django 3.0.12 on 2021-05-10 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0007_auto_20210510_2347'),
    ]

    operations = [
    ]
