# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-08 08:46


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0008_auto_20200228_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='techinfo',
            name='background_color',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='techinfo',
            name='end_blackout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='techinfo',
            name='follow_spot_color',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='techinfo',
            name='mic_choice',
            field=models.CharField(
                choices=[
                    (b"I don't need a mic", b"I don't need a mic"),
                    (b'I need a mic', b'I need a mic'),
                    (b'I own a mic', b'I own a mic')],
                default=(b"I don't need a mic", b"I don't need a mic"),
                max_length=200),
        ),
        migrations.AddField(
            model_name='techinfo',
            name='special_lighting_cue',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='techinfo',
            name='start_blackout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='techinfo',
            name='wash_color',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
