# Generated by Django 3.0.12 on 2021-04-27 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0008_auto_20210427_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='img',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='physical_address',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='publish_physical_address',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='website',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='business',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='gbe.Business'),
        ),
    ]
