# Generated by Django 3.0.12 on 2021-04-29 17:45

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('gbe', '0009_auto_20210427_2326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['name'], 'verbose_name_plural': 'businesses'},
        ),
        migrations.AlterField(
            model_name='business',
            name='img',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_business', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
