# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-08 22:11
from __future__ import unicode_literals

from django.db import migrations
from gbetext import mic_options


def centralize_adv_techinfo(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    TechInfo = apps.get_model('gbe', 'TechInfo')
    for techinfo in TechInfo.objects.all():
        if techinfo.audio.own_mic:
            techinfo.mic_choice = mic_options[2][0]
        elif techinfo.audio.need_mic:
            techinfo.mic_choice = mic_options[1][0]
        techinfo.save()


def decentralize_adv_techinfo(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    TechInfo = apps.get_model('gbe', 'TechInfo')
    for techinfo in TechInfo.objects.all():
        if techinfo.mic_choice == mic_options[2][0]:
            techinfo.audio.own_mic = True
        elif techinfo.mic_choice == mic_options[1][0]:
            techinfo.audio.need_mic = True
        techinfo.audio.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0009_auto_20200308_0846'),
    ]

    operations = [
        migrations.RunPython(centralize_adv_techinfo,
                             decentralize_adv_techinfo),
    ]
