# Generated by Django 3.0.12 on 2021-05-13 18:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0010_auto_20210429_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylevalue',
            name='opacity',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='stylevalue',
            name='value',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='MetaColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('style_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gbe.StyleVersion')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='stylevalue',
            name='meta_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gbe.MetaColor'),
        ),
        migrations.AddConstraint(
            model_name='metacolor',
            constraint=models.UniqueConstraint(fields=('style_version', 'name'), name='unique_meta_name'),
        ),
    ]
