# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-09 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0010_auto_20200308_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cueinfo',
            name='techinfo',
        ),
        migrations.RemoveField(
            model_name='techinfo',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='techinfo',
            name='lighting',
        ),
        migrations.RemoveField(
            model_name='techinfo',
            name='stage',
        ),
        migrations.DeleteModel(
            name='AudioInfo',
        ),
        migrations.DeleteModel(
            name='CueInfo',
        ),
        migrations.DeleteModel(
            name='LightingInfo',
        ),
        migrations.DeleteModel(
            name='StageInfo',
        ),
    ]
