# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-16 08:19
from __future__ import unicode_literals

from django.db import migrations, models
from gbetext import mic_options


def change_mic_default(apps, schema_editor):
    TechInfo = apps.get_model('gbe', 'TechInfo')
    for techinfo in TechInfo.objects.all():
        if techinfo.mic_choice == str(mic_options[0]):
            techinfo.mic_choice = mic_options[0][0]
            techinfo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0011_auto_20200309_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techinfo',
            name='mic_choice',
            field=models.CharField(
                choices=[(b"I don't need a mic", b"I don't need a mic"),
                         (b'I need a mic', b'I need a mic'),
                         (b'I own a mic', b'I own a mic')],
                default=b"I don't need a mic",
                max_length=200),
        ),
        migrations.RunPython(change_mic_default),
    ]
