# Generated by Django 3.0.14 on 2021-07-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0011_auto_20210517_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='techinfo',
            name='confirm_no_rehearsal',
            field=models.BooleanField(default=False),
        ),
    ]
