# Generated by Django 3.0.12 on 2021-05-13 18:19

from django.db import migrations


def initialize_style(apps, schema_editor):
    MetaColor = apps.get_model("gbe", "MetaColor")
    StyleVersion = apps.get_model("gbe", "StyleVersion")
    StyleSelector = apps.get_model("gbe", "StyleSelector")
    StyleProperty = apps.get_model("gbe", "StyleProperty")
    StyleValue = apps.get_model("gbe", "StyleValue")
    version = StyleVersion(
        name="Baseline",
        number=1.0,
        currently_live=True,
        currently_test=True)
    version.save()

    for select_val in init_values:
        selector = StyleSelector(
            selector=select_val['selector'],
            description=select_val['description'],
            pseudo_class=select_val['pseudo_class'],
            used_for=select_val['usage'])
        selector.save()
        for prop_val in select_val['prop_val']:
            val = prop_val[1]
            if len(prop_val) == 2:
                style_prop = StyleProperty(
                    selector=selector,
                    style_property=prop_val[0],
                    value_type='rgba')
            elif len(prop_val) == 3:
                style_prop = StyleProperty(
                    selector=selector,
                    style_property=prop_val[0],
                    value_type=prop_val[1])
                val = prop_val[2]
            else:
                raise Exception(
                    "there should be 2 or 3 values here" + str(select_val))
            style_prop.save()
            value = StyleValue(style_property=style_prop,
                               style_version=version,
                               value=val)
            value.save()


def destroy_style(apps, schema_editor):
    MetaColor = apps.get_model("gbe", "MetaColor")
    for select_val in init_values:
        StyleSelector.objects.filter(
            selector=select_val['selector'],
            pseudo_class=select_val['pseudo_class']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0011_auto_20210513_1818'),
    ]

    operations = [
        migrations.RunPython(initialize_style, reverse_code=destroy_style),
    ]
