# Generated by Django 3.0.14 on 2021-07-27 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0012_techinfo_confirm_no_rehearsal'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('test_notes', models.TextField(blank=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TestURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=128, unique=True)),
                ('partial_url', models.CharField(max_length=300, unique=True)),
                ('test_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.AddField(
            model_name='styleproperty',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StyleLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('help_text', models.CharField(max_length=500)),
                ('order', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gbe.StyleGroup')),
            ],
            options={
                'ordering': ['group__order', 'order'],
            },
        ),
        migrations.AddField(
            model_name='stylegroup',
            name='test_urls',
            field=models.ManyToManyField(blank=True, to='gbe.TestURL'),
        ),
        migrations.CreateModel(
            name='StyleElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField()),
                ('sample_html', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gbe.StyleGroup')),
            ],
            options={
                'ordering': ['group', 'name'],
            },
        ),
        migrations.AddField(
            model_name='styleproperty',
            name='element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gbe.StyleElement'),
        ),
        migrations.AddField(
            model_name='styleproperty',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gbe.StyleLabel'),
        ),
        migrations.AddConstraint(
            model_name='stylelabel',
            constraint=models.UniqueConstraint(fields=('name', 'group'), name='label_unique_name'),
        ),
        migrations.AddConstraint(
            model_name='stylelabel',
            constraint=models.UniqueConstraint(fields=('order', 'group'), name='label_unique_order'),
        ),
        migrations.AddConstraint(
            model_name='styleelement',
            constraint=models.UniqueConstraint(fields=('name', 'group'), name='element_unique_name'),
        ),
        migrations.AddConstraint(
            model_name='styleelement',
            constraint=models.UniqueConstraint(fields=('order', 'group'), name='element_unique_order'),
        ),
    ]
