# Generated by Django 3.0.14 on 2021-07-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0012_techinfo_confirm_no_rehearsal'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(max_length=128)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
            ],
        ),
    ]
