# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-22 21:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20200422_2149'),
        ('gbe', '0012_auto_20200316_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='combo',
            name='performer_ptr',
        ),
        migrations.AlterField(
            model_name='act',
            name='video_choice',
            field=models.CharField(blank=True, choices=[('0', "I don't have any video of myself performing"), ('1', "This is video of me but not the act I'm submitting"), ('2', 'This is video of the act I would like to perform')], max_length=2),
        ),
        migrations.AlterField(
            model_name='biddable',
            name='accepted',
            field=models.IntegerField(choices=[(0, 'No Decision'), (1, 'Reject'), (2, 'Wait List'), (3, 'Accepted'), (4, 'Withdrawn'), (5, 'Duplicate')], default=0),
        ),
        migrations.AlterField(
            model_name='bidevaluation',
            name='vote',
            field=models.IntegerField(choices=[(1, 'Strong yes'), (2, 'Yes'), (3, 'Weak Yes'), (4, 'No Comment'), (5, 'Weak No'), (6, 'No'), (7, 'Strong No'), (-1, 'Abstain')]),
        ),
        migrations.AlterField(
            model_name='class',
            name='length_minutes',
            field=models.IntegerField(blank=True, choices=[(60, '60'), (90, '90'), (120, '120')], default=60),
        ),
        migrations.AlterField(
            model_name='class',
            name='multiple_run',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20),
        ),
        migrations.AlterField(
            model_name='class',
            name='space_needs',
            field=models.CharField(blank=True, choices=[('Movement Class Floor', (('0', "Don't Care about Floor"), ('1', 'Carpet'), ('2', 'Dance Floor'), ('3', 'Both'))), ('Lecture Class Setup', (('4', "Don't Care about Seating"), ('5', 'Lecture Style - tables and chairs face podium'), ('6', 'Conversational - seating in a ring')))], default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='class',
            name='type',
            field=models.CharField(blank=True, choices=[('Lecture', 'Lecture'), ('Movement', 'Movement'), ('Panel', 'Panel'), ('Workshop', 'Workshop')], default='Lecture', max_length=128),
        ),
        migrations.AlterField(
            model_name='classproposal',
            name='type',
            field=models.CharField(choices=[('Class', 'Class'), ('Panel', 'Panel'), ('Either', 'Either')], default='Class', max_length=20),
        ),
        migrations.AlterField(
            model_name='conference',
            name='act_style',
            field=models.CharField(choices=[('normal', 'normal'), ('summer', 'summer')], default='normal', max_length=50),
        ),
        migrations.AlterField(
            model_name='conference',
            name='status',
            field=models.CharField(choices=[('upcoming', 'upcoming'), ('ongoing', 'ongoing'), ('completed', 'completed')], default='upcoming', max_length=50),
        ),
        migrations.AlterField(
            model_name='conferencevolunteer',
            name='how_volunteer',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Moderator', 'Moderator'), ('Panelist', 'Panelist'), ('Any of the Above', 'Any of the Above')], default='Any of the Above', max_length=20),
        ),
        migrations.AlterField(
            model_name='conferencevolunteer',
            name='qualification',
            field=models.TextField(blank='True'),
        ),
        migrations.AlterField(
            model_name='costume',
            name='active_use',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='costume',
            name='pasties',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='costume',
            name='picture',
            field=models.FileField(blank=True, upload_to='uploads/images'),
        ),
        migrations.AlterField(
            model_name='genericevent',
            name='type',
            field=models.CharField(choices=[('Special', 'Special Event'), ('Volunteer', 'Volunteer Opportunity'), ('Master', 'Master Class'), ('Drop-In', 'Drop-In Class'), ('Rehearsal Slot', 'Rehearsal Slot')], default='Special', max_length=128),
        ),
        migrations.AlterField(
            model_name='performerfestivals',
            name='experience',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ('Won', 'Yes - and Won!')], default='No', max_length=20),
        ),
        migrations.AlterField(
            model_name='performerfestivals',
            name='festival',
            field=models.CharField(choices=[('GBE', 'The Great Burlesque Exposition'), ('BHOF', 'Miss Exotic World/Burlesque Hall of Fame'), ('NYBF', 'New York Burlesque Festival'), ('NOBF', 'New Orleans Burlesque Festival'), ('TBF', 'Texas Burlesque Festival')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='best_time',
            field=models.CharField(blank=True, choices=[('Any', 'Any'), ('Mornings', 'Mornings'), ('Afternoons', 'Afternoons'), ('Evenings', 'Evenings')], default='Any', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Phone numbers must be in a standard US format, such as ###-###-###.', regex='(\\d{3}[-\\.]?\\d{3}[-\\.]?\\d{4})')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='purchase_email',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('OTHER', 'Other/Non-US')], max_length=2),
        ),
        migrations.AlterField(
            model_name='profilepreferences',
            name='in_hotel',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Maybe', 'Maybe')], max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='address',
            field=models.TextField(blank=True, help_text='This can include HTML, and it will be for formatting.', max_length=500),
        ),
        migrations.AlterField(
            model_name='room',
            name='map_embed',
            field=models.TextField(blank=True, help_text='Use the embedded map instructions and this will display on event pages.  With Google, small size is recommended.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='show',
            name='cue_sheet',
            field=models.CharField(choices=[('Theater', 'Theater'), ('Alternate', 'Alternate'), ('None', 'None')], default='Theater', max_length=128),
        ),
        migrations.AlterField(
            model_name='showvote',
            name='vote',
            field=models.IntegerField(blank=True, choices=[(1, 'Strong yes'), (2, 'Yes'), (3, 'Weak Yes'), (4, 'No Comment'), (5, 'Weak No'), (6, 'No'), (7, 'Strong No'), (-1, 'Abstain')], null=True),
        ),
        migrations.AlterField(
            model_name='staffarea',
            name='default_volunteers',
            field=models.IntegerField(blank=True, default='1', null=True),
        ),
        migrations.AlterField(
            model_name='techinfo',
            name='mic_choice',
            field=models.CharField(choices=[("I don't need a mic", "I don't need a mic"), ('I need a mic', 'I need a mic'), ('I own a mic', 'I own a mic')], default="I don't need a mic", max_length=200),
        ),
        migrations.AlterField(
            model_name='techinfo',
            name='track',
            field=models.FileField(blank=True, upload_to='uploads/audio'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='level',
            field=models.CharField(blank=True, choices=[('Featured', 'Featured')], default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='want_help',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='pre_event',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='volunteerinterest',
            name='rank',
            field=models.IntegerField(blank=True, choices=[(0, '--------------'), (1, 'Not interested'), (2, 'Slightly interested'), (3, 'Neither interested nor disinterested'), (4, 'Somewhat interested'), (5, 'Strongly interested')]),
        ),
        migrations.DeleteModel(
            name='Combo',
        ),
    ]
