# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-12 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0013_auto_20200422_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerwindow',
            name='day',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='available_windows',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='unavailable_windows',
        ),
        migrations.DeleteModel(
            name='VolunteerWindow',
        ),
    ]
