# Generated by Django 3.0.8 on 2020-08-18 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0015_auto_20200714_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='act',
            name='actitem_ptr',
        ),
    ]
