# Generated by Django 3.0.14 on 2021-08-10 09:29

from django.db import migrations


from django.urls import reverse


def initialize_style(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    StyleElement = apps.get_model("gbe", "StyleElement")
    StyleLabel = apps.get_model("gbe", "StyleLabel")
    TestURL = apps.get_model("gbe", "TestURL")
    StyleGroup = apps.get_model("gbe", "StyleGroup")
    StyleSelector = apps.get_model("gbe", "StyleSelector")
    StyleProperty = apps.get_model("gbe", "StyleProperty")
    StyleValue = apps.get_model("gbe", "StyleValue")

    group1 = StyleGroup(
        name="Alerts",
        test_notes="Alerts are mostly seen in response to activities on a " +
        "page.  To see all the colors at work, sucessfully do an operation, " +
        "do something to trigger a warning (overbooking a user works), and " +
        "generate an error.",
        order=1)
    group1.save()
    url1 = TestURL.objects.get(display_name="Personal Home Page")
    group1.test_urls.add(url1)
    danger_alert = StyleElement(
        name="Danger Alert",
        group=group1,
        description="Something has gone wrong so badly the operation cannot " +
        "be completed.  Red is common for this.",
        order=5,
        sample_html='<div class="alert gbe-alert-danger"><a href="#" ' +
        'class="close" data-dismiss="alert" aria-label="close">&times;</a>' +
        '<strong>Danger:</strong> alert text here</div>')
    danger_alert.save()
    warning_alert = StyleElement(
        name="Warning Alert",
        group=group1,
        description="Warnings don't block activity, but are reasons to be " +
        "aware.",
        order=10,
        sample_html='<div class="alert gbe-alert-warning"><a href="#" ' +
        'class="close" data-dismiss="alert" aria-label="close">&times;</a>' +
        '<strong>Warning:</strong> alert text here</div>')
    warning_alert.save()
    information_alert = StyleElement(
        name="Information Alert",
        group=group1,
        description="Information which is not good or bad, just FYI.",
        order=15,
        sample_html='<div class="alert gbe-alert-info"><a href="#" ' +
        'class="close" data-dismiss="alert" aria-label="close">&times;</a>' +
        '<strong>Info:</strong> alert text here</div>')
    information_alert.save()
    success_alert = StyleElement(
        name="Success Alert",
        group=group1,
        description="A function was completed successfully.",
        order=20,
        sample_html='<div class="alert gbe-alert-success"><a href="#" ' +
        'class="close" data-dismiss="alert" aria-label="close">&times;</a>' +
        '<strong>Success:</strong> alert text here</div>')
    success_alert.save()
    profile_alert = StyleElement(
        name="Profile Page Alert",
        group=group1,
        description="Shown on profile page, if the user has an act with " +
        "incomplete act tech info.",
        order=25,
        sample_html="<div class='gbe-alert'>Act Tech Alert<br><br> </div>")
    profile_alert.save()
    background = StyleLabel(
        name="Background",
        group=group1,
        order=5)
    background.save()
    border = StyleLabel(
        name="Border",
        group=group1,
        order=10)
    border.save()
    text_color = StyleLabel(
        name="Text Color",
        group=group1,
        order=20)
    text_color.save()

    # danger
    v1 = StyleProperty.objects.get(pk=13)
    v1.element = danger_alert
    v1.label = background
    v1.save()
    v2 = StyleProperty.objects.get(pk=14)
    v2.element = danger_alert
    v2.label = border
    v2.save()
    v3 = StyleProperty.objects.get(pk=15)
    v3.element = danger_alert
    v3.label = text_color
    v3.save()

    # warning
    v4 = StyleProperty.objects.get(pk=22)
    v4.element = warning_alert
    v4.label = background
    v4.save()
    v5 = StyleProperty.objects.get(pk=23)
    v5.element = warning_alert
    v5.label = border
    v5.save()
    v6 = StyleProperty.objects.get(pk=24)
    v6.element = warning_alert
    v6.label = text_color
    v6.save()

    # info
    v7 = StyleProperty.objects.get(pk=16)
    v7.element = information_alert
    v7.label = background
    v7.save()
    v8 = StyleProperty.objects.get(pk=17)
    v8.element = information_alert
    v8.label = border
    v8.save()
    v9 = StyleProperty.objects.get(pk=18)
    v9.element = information_alert
    v9.label = text_color
    v9.save()

    # success
    v10 = StyleProperty.objects.get(pk=19)
    v10.element = success_alert
    v10.label = background
    v10.save()
    v11 = StyleProperty.objects.get(pk=20)
    v11.element = success_alert
    v11.label = border
    v11.save()
    v12 = StyleProperty.objects.get(pk=21)
    v12.element = success_alert
    v12.label = text_color
    v12.save()

    # profile
    v10 = StyleProperty.objects.get(pk=256)
    v10.element = profile_alert
    v10.label = background
    v10.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0015_auto_20210802_0716'),
    ]

    operations = [
        migrations.RunPython(initialize_style),
    ]
