# Generated by Django 3.0.14 on 2021-08-14 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0016_auto_20210810_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencevolunteer',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='conferencevolunteer',
            name='presenter',
        ),
        migrations.DeleteModel(
            name='ClassProposal',
        ),
        migrations.DeleteModel(
            name='ConferenceVolunteer',
        ),
    ]
