# Generated by Django 3.0.14 on 2022-10-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0018_auto_20210827_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='performer',
            name='year_started',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='performer',
            name='experience',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='PerformerFestivals',
        ),
    ]
