# Generated by Django 3.2.16 on 2022-11-07 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0019_auto_20221001_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Phone numbers must be in a standard US format, such as ###-###-####.', regex='(\\d{3}[-\\.]?\\d{3}[-\\.]?\\d{4})')]),
        ),
    ]
