# Generated by Django 3.2.16 on 2022-11-22 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0020_alter_profile_phone'),
        ('ticketing', '0012_auto_20221118_2358')
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='default_location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='e_conference',
        ),
        migrations.RemoveField(
            model_name='event',
            name='eventitem_ptr',
        ),
        migrations.RemoveField(
            model_name='genericevent',
            name='event_ptr',
        ),
        migrations.RemoveField(
            model_name='show',
            name='event_ptr',
        ),
        migrations.RemoveField(
            model_name='showvote',
            name='show',
        ),
        migrations.RemoveField(
            model_name='actbidevaluation',
            name='primary_vote',
        ),
        migrations.RemoveField(
            model_name='actbidevaluation',
            name='secondary_vote',
        ),
        migrations.RemoveField(
            model_name='class',
            name='event_ptr',
        ),
    ]
