# Generated by Django 3.2.16 on 2022-11-22 21:35

from django.db import migrations
from django.db.migrations.operations.base import Operation


class AlterBaseOperation(Operation):
    reduce_to_sql = False
    reversible = True

    def __init__(self, model_name, bases, prev_bases):
        self.model_name = model_name
        self.bases = bases
        self.prev_bases = prev_bases

    def state_forwards(self, app_label, state):
        state.models[app_label, self.model_name].bases = self.bases
        state.reload_model(app_label, self.model_name)

    def state_backwards(self, app_label, state):
        state.models[app_label, self.model_name].bases = self.prev_bases
        state.reload_model(app_label, self.model_name)

    def database_forwards(self,
                          app_label,
                          schema_editor,
                          from_state,
                          to_state):
        pass

    def database_backwards(self,
                           app_label,
                           schema_editor,
                           from_state,
                           to_state):
        pass

    def describe(self):
        return "Update %s bases to %s" % (self.model_name, self.bases)


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0020_alter_profile_phone'),
        ('ticketing', '0012_auto_20221118_2358')
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='default_location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='e_conference',
        ),
        migrations.RemoveField(
            model_name='event',
            name='eventitem_ptr',
        ),
        migrations.RemoveField(
            model_name='genericevent',
            name='event_ptr',
        ),
        migrations.RemoveField(
            model_name='show',
            name='event_ptr',
        ),
        migrations.RemoveField(
            model_name='showvote',
            name='show',
        ),
        migrations.RemoveField(
            model_name='actbidevaluation',
            name='primary_vote',
        ),
        migrations.RemoveField(
            model_name='actbidevaluation',
            name='secondary_vote',
        ),
        migrations.RemoveField(
            model_name='class',
            name='event_ptr',
        ),
        AlterBaseOperation(model_name='class',
                           bases=('gbe.biddable',),
                           prev_bases=('gbe.biddable', 'gbe.event'))
    ]
