# Generated by Django 3.2.16 on 2023-01-11 06:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0022_auto_20221122_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(null=True)),
                ('username', models.CharField(max_length=100, null=True)),
                ('socal_network', models.CharField(blank=True, choices=[('Cash App', 'Cash App'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Paypal', 'Paypal'), ('TikTok', 'TikTok'), ('Venmo', 'Venmo'), ('Website', 'Website'), ('YouTube', 'YouTube')], max_length=40)),
                ('order', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='gbe.performer')),
            ],
            options={
                'ordering': ['performer', 'order'],
                'unique_together': {('socal_network', 'link')},
            },
        ),
    ]
