# Generated by Django 3.2.16 on 2023-01-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0022_auto_20221122_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplatesender',
            name='from_name',
            field=models.CharField(default='Team BurlExpo', max_length=150),
            preserve_default=False,
        ),
    ]
