# Generated by Django 3.2.16 on 2023-01-23 20:34

from django.db import migrations


def migrate_homepage(apps, schema_editor):
    Performer = apps.get_model("gbe", "Performer")
    SocialLink = apps.get_model("gbe", "SocialLink")

    for performer in Performer.objects.exclude(homepage__exact=''):
        link = SocialLink(order=1,
                          performer=performer,
                          social_network="Website",
                          link=performer.homepage)
        link.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0023_sociallink'),
    ]

    operations = [
        migrations.RunPython(migrate_homepage)
    ]
