# Generated by Django 3.2.16 on 2023-01-23 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0024_migrate_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performer',
            name='homepage',
        ),
    ]
