# Generated by Django 3.2.16 on 2023-01-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0025_remove_performer_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='performer',
            name='pronouns',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
