# Generated by Django 3.2.16 on 2023-01-24 07:46

from django.db import migrations


def migrate_pronouns(apps, schema_editor):
    TechInfo = apps.get_model("gbe", "TechInfo")

    for tech in TechInfo.objects.exclude(pronouns__exact=''):
        performer = tech.act.performer
        performer.pronouns = tech.pronouns
        performer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0026_performer_pronouns'),
    ]

    operations = [
        migrations.RunPython(migrate_pronouns)
    ]
