# Generated by Django 3.2.16 on 2023-01-24 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0027_migrate_pronoun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techinfo',
            name='pronouns',
        ),
    ]
