# Generated by Django 3.2.16 on 2023-02-04 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0029_emailtemplatesender_from_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sociallink',
            unique_together=set(),
        ),
    ]
