# Generated by Django 3.2.18 on 2023-04-05 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0030_alter_sociallink_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddable',
            name='accepted',
            field=models.IntegerField(choices=[(0, 'No Decision'), (1, 'Reject'), (2, 'Wait List'), (3, 'Accepted'), (4, 'Withdrawn'), (5, 'Duplicate'), (6, 'Awaiting Approval')], default=0),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_status', models.SmallIntegerField(choices=[(0, 'Never Available'), (1, 'Available Now'), (2, 'Available after "Publish Date"')], default=1, verbose_name='Publish')),
                ('live_as_of', models.DateTimeField(blank=True, null=True, verbose_name='Publish Date')),
                ('title', models.CharField(max_length=128)),
                ('summary', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gbe.profile')),
            ],
        ),
    ]
