# Generated by Django 3.2.18 on 2023-04-08 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('gbe', '0031_auto_20230405_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='gbe_articleconfig', serialize=False, to='cms.cmsplugin')),
                ('num_articles', models.IntegerField(default=4)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
