# Generated by Django 3.2.18 on 2023-05-12 10:24

from django.db import migrations


def move_performer(performer, bio):
    # Move act proposals
    for act in performer.acts.all():
        act.bio = bio
        act.save()

    # Move social links
    for link in performer.links.all():
        link.bio = bio
        link.save()


def migrate_personas(apps, schema_editor):
    Bio = apps.get_model("gbe", "Bio")
    Persona = apps.get_model("gbe", "Persona")
    for performer in Persona.objects.all():
        # move persona to bio
        bio = Bio(contact=performer.contact,
                  name=performer.name,
                  label=performer.label,
                  bio=performer.bio,
                  experience=performer.experience,
                  year_started=performer.year_started,
                  awards=performer.awards,
                  img=performer.img,
                  festivals=performer.festivals,
                  pronouns=performer.pronouns)
        bio.save()
        # Move class proposals
        for class_bid in performer.is_teaching.all():
            class_bid.teacher_bio = bio
            class_bid.save()

        # Move costume proposals
        for costume in performer.costume_set.all():
            costume.bio = bio
            costume.save()
        move_performer(performer, bio)


def migrate_troupes(apps, schema_editor):
    Bio = apps.get_model("gbe", "Bio")
    Troupe = apps.get_model("gbe", "Troupe")
    for performer in Troupe.objects.all():
        # move persona to bio
        bio = Bio(contact=performer.contact,
                  name=performer.name,
                  label=performer.label,
                  bio=performer.bio,
                  experience=performer.experience,
                  year_started=performer.year_started,
                  awards=performer.awards,
                  img=performer.img,
                  festivals=performer.festivals,
                  pronouns=performer.pronouns)
        bio.save()
        move_performer(performer, bio)


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0033_new_bios'),
        ('scheduler', '0011_new_bios'),
    ]

    operations = [
        migrations.RunPython(migrate_personas),
        migrations.RunPython(migrate_troupes)
    ]
