# Generated by Django 3.2.18 on 2023-05-15 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0034_move_bios'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='performer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='performer',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='performer',
            name='img',
        ),
        migrations.RemoveField(
            model_name='performer',
            name='workeritem_ptr',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='performer_profile',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='performer_ptr',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_object',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='workeritem_ptr',
        ),
        migrations.RemoveField(
            model_name='troupe',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='troupe',
            name='performer_ptr',
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ['bio', 'order']},
        ),
        migrations.RemoveField(
            model_name='act',
            name='performer',
        ),
        migrations.RemoveField(
            model_name='actbidevaluation',
            name='evaluator',
        ),
        migrations.RemoveField(
            model_name='article',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='bidevaluation',
            name='evaluator',
        ),
        migrations.RemoveField(
            model_name='business',
            name='owners',
        ),
        migrations.RemoveField(
            model_name='class',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='costume',
            name='performer',
        ),
        migrations.RemoveField(
            model_name='costume',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profilepreferences',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='performer',
        ),
        migrations.RemoveField(
            model_name='staffarea',
            name='staff_lead',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='profile',
        ),
        migrations.AlterUniqueTogether(
            name='flexibleevaluation',
            unique_together={('bid', 'evaluator_acct', 'category')},
        ),
    ]
