# Generated by Django 3.2.18 on 2023-05-15 20:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gbe', '0036_remove_worker_models'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='actbidevaluation',
            old_name='evaluator_acct',
            new_name='evaluator',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='creator_acct',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='bidevaluation',
            old_name='evaluator_acct',
            new_name='evaluator',
        ),
        migrations.RenameField(
            model_name='costume',
            old_name='account',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='flexibleevaluation',
            old_name='evaluator_acct',
            new_name='evaluator',
        ),
        migrations.RenameField(
            model_name='profilepreferences',
            old_name='account',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='staffarea',
            old_name='staff_lead_account',
            new_name='staff_lead',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='account',
            new_name='profile',
        ),
        migrations.RemoveField(
            model_name='business',
            name='owner_accts',
        ),
        migrations.AddField(
            model_name='business',
            name='owners',
            field=models.ManyToManyField(to='gbe.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='flexibleevaluation',
            unique_together={('bid', 'evaluator', 'category')},
        ),
    ]
