# Generated by Django 3.2.18 on 2023-05-16 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0037_account_to_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actbidevaluation',
            name='evaluator',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='gbe.profile'),
        ),
        migrations.AlterField(
            model_name='bidevaluation',
            name='evaluator',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='gbe.profile'),
        ),
        migrations.AlterField(
            model_name='costume',
            name='profile',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='costumes',
                to='gbe.profile'),
        ),
        migrations.AlterField(
            model_name='flexibleevaluation',
            name='evaluator',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='gbe.profile'),
        ),
        migrations.AlterField(
            model_name='profilepreferences',
            name='profile',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='preferences',
                to='gbe.profile'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='profile',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='volunteering',
                to='gbe.profile'),
        ),
    ]
