# Generated by Django 3.2.18 on 2023-05-19 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0038_lock_back_down'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='teacher_bio',
            field=models.ForeignKey(default=51, on_delete=django.db.models.deletion.CASCADE, related_name='is_teaching', to='gbe.bio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='bio',
            field=models.ForeignKey(default=51, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='gbe.bio'),
            preserve_default=False,
        ),
    ]
