# Generated by Django 3.2.18 on 2023-07-13 19:49

from django.db import migrations


def clean_bad_social_links(apps, schema_editor):
    SocialLink = apps.get_model("gbe", "SocialLink")
    count = 0
    for link in SocialLink.objects.all().order_by('-pk'):
        if SocialLink.objects.filter(
                 bio=link.bio,
                 link=link.link, 
                 username=link.username,
                 social_network=link.social_network).exclude(
                 pk=link.pk).exists():
            print("Link order: %d, pk: %d for user %s, bio id: %s" % (
                link.order,
                link.pk,
                link.bio.name,
                link.bio.pk,
                ))
            link.delete()
            count = count + 1
    print("Deleted %d links" % count)


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0039_auto_20230519_2133'),
    ]

    operations = [
        migrations.RunPython(clean_bad_social_links),
    ]
