# Generated by Django 3.2.18 on 2023-07-13 19:49

from django.db import migrations


def clean_bad_social_links(apps, schema_editor):
    SocialLink = apps.get_model("gbe", "SocialLink")
    Bio = apps.get_model("gbe", "Bio")
    count = 0
    print("")
    for link in SocialLink.objects.all().order_by('-pk'):
        if SocialLink.objects.filter(
                 bio=link.bio,
                 link=link.link, 
                 username=link.username,
                 social_network=link.social_network).exclude(
                 pk=link.pk).exists():
            print("Link order: %d, pk: %d for user %s, bio id: %s" % (
                link.order,
                link.pk,
                link.bio.name,
                link.bio.pk,
                ))
            link.delete()
            count = count + 1
    for bio in Bio.objects.all():
        i = 1
        for link in bio.links.all():
            if link.order != i:
                link.order = i
                link.save()
            i = i + 1
            if link.order > 5:
                print("problem for %s - link greater than 5" % bio.name)


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0040_volunteerevaluation'),
    ]

    operations = [
        migrations.RunPython(clean_bad_social_links),
    ]
