# Generated by Django 3.2.18 on 2023-09-05 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0041_clean_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='num_performers',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='act',
            name='performer_names',
            field=models.TextField(blank=True),
        ),
    ]
