# Generated by Django 3.2.18 on 2023-10-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0042_auto_20230905_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=128),
        ),
    ]
