# Generated by Django 3.2.18 on 2023-10-22 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0043_clear_summer_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='act_style',
        ),
    ]
