# Generated by Django 3.2.18 on 2023-10-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0044_remove_conference_act_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=128),
        ),
        migrations.AddField(
            model_name='class',
            name='labels',
            field=models.ManyToManyField(to='gbe.ClassLabel'),
        ),
    ]
