# Generated by Django 3.2.18 on 2023-10-25 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0044_remove_conference_act_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=128),
        ),
        migrations.CreateModel(
            name='ClassLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=200)),
                ('class_bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gbe.class')),
            ],
            options={
                'unique_together': {('text', 'class_bid')},
            },
        ),
    ]
