# Generated by Django 3.2.23 on 2024-01-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0046_auto_20231128_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='accepting_bids',
            field=models.TextField(blank=True),
        ),
    ]
