from django.urls import re_path
from gbe.scheduling.views import (
    ApproveVolunteerView,
    ClassWizardView,
    CopyOccurrenceView,
    CopyStaffAreaView,
    DeleteEventView,
    EditClassView,
    EditEventView,
    EditShowView,
    EditStaffAreaView,
    EditVolunteerView,
    EvalEventView,
    EventDetailView,
    EventWizardView,
    ListEventsView,
    ManageConferenceView,
    ManageEventsView,
    RehearsalWizardView,
    SetFavoriteView,
    SetVolunteerView,
    ShowCalendarView,
    ShowDashboard,
    StaffAreaWizardView,
    TicketedEventWizardView,
    VolunteerAutocomplete,
    VolunteerSignupView,
    VolunteerWizardView,
)

# NOTE: in general, url patterns should end with '/?$'. This
# means "match the preceding patter, plus an optional final '?',
# and no other characters following. So '^foo/?$' matches on
# "foo" or "foo/", but not on "foo/bar" or "foo!".
# Which is what we usually want.
app_name = "scheduling"

urlpatterns = [
    re_path(r'^conference/manage/(?P<day_id>\d+)/?$',
            ManageConferenceView.as_view(),
            name='schedule_conference'),
    re_path(r'^conference/manage/?$',
            ManageConferenceView.as_view(),
            name='manage_conference'),

    re_path(r'^scheduling/manage/?$',
            ManageEventsView.as_view(),
            name='manage_event_list'),
    re_path(r'^scheduling/manage/(?P<conference_slug>[-\w]+)/?$',
            ManageEventsView.as_view(),
            name='manage_event_list'),
    re_path(r'^scheduler/delete_occurrence/(?P<occurrence_id>\d+)/?$',
            DeleteEventView.as_view(),
            name='delete_occurrence'),
    re_path(r'^scheduling/show_dashboard/(?P<occurrence_id>\d+)/?$',
            ShowDashboard.as_view(),
            name='show_dashboard'),

    re_path(r'^scheduling/create_class_wizard/(?P<conference>[-\w]+)/?$',
            ClassWizardView.as_view(),
            name='create_class_wizard'),
    re_path(r'^scheduling/create_staff_area_wizard/(?P<conference>[-\w]+)/?$',
            StaffAreaWizardView.as_view(),
            name='staff_area_wizard'),
    re_path(r'^scheduling/create_rehearsal_wizard/(?P<conference>[-\w]+)/?$',
            RehearsalWizardView.as_view(),
            name='rehearsal_wizard'),
    re_path(r'^scheduling/create_ticketed_wizard/(?P<conference>[-\w]+)/' +
            '(?P<event_type>[-\w]+)/?$',
            TicketedEventWizardView.as_view(),
            name='create_ticketed_event_wizard'),
    re_path(r'^scheduling/create_volunteer_wizard/(?P<conference>[-\w]+)/?$',
            VolunteerWizardView.as_view(),
            name='create_volunteer_wizard'),
    re_path(r'^scheduling/create_event_wizard/(?P<conference>[-\w]+)/?$',
            EventWizardView.as_view(),
            name='create_event_wizard'),
    re_path(
        r'^scheduling/edit/(?P<conference>[-\w]+)/(?P<occurrence_id>\d+)/?$',
        EditEventView.as_view(),
        name='edit_event'),
    re_path(r'^scheduling/show_edit/(?P<conference>[-\w]+)/' +
            '(?P<occurrence_id>\d+)/?$',
            EditShowView.as_view(),
            name='edit_show'),
    re_path(r'^scheduling/class_edit/(?P<conference>[-\w]+)/' +
            '(?P<occurrence_id>\d+)/?$',
            EditClassView.as_view(),
            name='edit_class'),
    re_path(r'^scheduling/volunteer_edit/(?P<conference>[-\w]+)/' +
            '(?P<occurrence_id>\d+)/?$',
            EditVolunteerView.as_view(),
            name='edit_volunteer'),
    re_path(r'^scheduling/staff_edit/(?P<staff_id>\d+)/?$',
            EditStaffAreaView.as_view(),
            name='edit_staff'),
    re_path(r'^scheduling/manage-show-opps/(?P<conference>[-\w]+)/' +
            '(?P<occurrence_id>\d+)/?$',
            EditShowView.as_view(),
            name='manage_show_opp'),
    re_path(r'^scheduling/manage-opps/(?P<conference>[-\w]+)/' +
            '(?P<occurrence_id>\d+)/?$',
            EditEventView.as_view(),
            name='manage_vol'),
    re_path(r'^scheduling/manage-opps/(?P<staff_id>\d+)/?$',
            EditStaffAreaView.as_view(),
            name='manage_vol'),
    re_path(r'^scheduling/manage-workers/(?P<conference>[-\w]+)/' +
            '(?P<occurrence_id>\d+)/?$',
            EditVolunteerView.as_view(),
            name='manage_workers'),

    re_path(r'^scheduling/copy/(?P<occurrence_id>\d+)/?$',
            CopyOccurrenceView.as_view(),
            name='copy_event_schedule'),
    re_path(r'^scheduling/copy_staff/(?P<staff_id>\d+)/?$',
            CopyStaffAreaView.as_view(),
            name='copy_staff_schedule'),

    re_path(r'^scheduling/volunteer_signup/?$',
            VolunteerSignupView.as_view(),
            name='volunteer_signup'),
    re_path(r'^volunteer/review_pending/?$',
            ApproveVolunteerView.as_view(),
            name='review_pending'),
    re_path(r'^volunteer/(?P<action>approve|waitlist|reject)/' +
            '(?P<public_id>\d+)/(?P<booking_id>\d+)/?$',
            ApproveVolunteerView.as_view(),
            name='approve_volunteer'),
    re_path(
        r'^calendar/(?P<calendar_type>[-\w]+)/(?P<day>\d{2}-\d{2}-\d{4})/?$',
        ShowCalendarView.as_view(),
        name='calendar_by_day'),
    re_path(r'^calendar/(?P<calendar_type>[-\w]+)/?$',
            ShowCalendarView.as_view(),
            name='calendar'),
    re_path(r'^scheduling/evaluate/(?P<occurrence_id>\d+)/?$',
            EvalEventView.as_view(),
            name='eval_event'),
    re_path(
        r'^scheduling/favorite/(?P<occurrence_id>\d+)/(?P<state>on|off)/?$',
        SetFavoriteView.as_view(),
        name='set_favorite'),
    re_path(
        r'^scheduling/volunteer/(?P<occurrence_id>\d+)/(?P<state>on|off)/?$',
        SetVolunteerView.as_view(),
        name='set_volunteer'),
    re_path(r'^scheduling/view_list/?$',
            ListEventsView.as_view(),
            name='event_list'),
    re_path(r'^scheduling/view_list/(?P<event_type>[-\w]+)/?$',
            ListEventsView.as_view(),
            name='event_list'),
    re_path(r'^scheduling/details/(?P<occurrence_id>\d+)/?$',
            EventDetailView.as_view(),
            name='detail_view'),

    re_path(r'^volunteer-autocomplete/$',
            VolunteerAutocomplete.as_view(),
            name='volunteer-autocomplete'),
]
