# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-31 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='approval_needed',
            field=models.BooleanField(default=False),
        ),
    ]
