# Generated by Django 3.0.12 on 2021-02-20 19:48

from django.db import migrations

def fix_volunteer_or_act(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Event = apps.get_model("scheduler", "Event")
    gbe_Event = apps.get_model("gbe", "GenericEvent")
    rehearsals = gbe_Event.objects.filter(type="Rehearsal Slot")
    rehearsal_count = 0
    volunteer_opps = 0
    for event in Event.objects.all():
        if event.max_volunteer == event.max_commitments and (
        	        event.max_volunteer > 0):
            if rehearsals.filter(eventitem_id=event.eventitem_id).exists():
            	event.max_volunteer = 0
            	rehearsal_count = rehearsal_count + 1
            else:
            	event.max_commitments = 0
            	volunteer_opps = volunteer_opps + 1
            event.save()
    print("Updated %d rehearsals and %d volunteer slots" % (
    	rehearsal_count,
    	volunteer_opps))

class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20200913_1621'),
    ]

    operations = [
        migrations.RunPython(fix_volunteer_or_act)
    ]
