# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-13 19:54
from __future__ import unicode_literals

from django.db import migrations
from datetime import datetime, timedelta


def reschedule_gbe_2020(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Event = apps.get_model('scheduler', 'Event')
    for event in Event.objects.filter(starttime__gt=datetime(2020, 1, 1)):
        event.starttime = event.starttime + timedelta(days=140)
        event.save()


def back_to_the_future(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Event = apps.get_model('scheduler', 'Event')
    for event in Event.objects.filter(starttime__gt=datetime(2020, 1, 1)):
        event.starttime = event.starttime - timedelta(days=140)
        event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20200119_1424'),
    ]

    operations = [
        migrations.RunPython(reschedule_gbe_2020, back_to_the_future),
    ]
