# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-05 14:19
from __future__ import unicode_literals

from django.db import migrations


def clean_resources(apps, schema_editor):
    Resource = apps.get_model('scheduler', 'Resource')
    counter = 0
    for resource in Resource.objects.all():
        if resource.allocations and resource.allocations.count() == 0:
            counter = counter + 1
            resource.delete()
    print "Deleted %d resources" % counter


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_auto_20200313_1954'),
    ]

    operations = [
        migrations.RunPython(clean_resources),
    ]
