# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-22 21:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_auto_20200405_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventevalgrade',
            name='answer',
            field=models.IntegerField(blank=True, choices=[(4, 'A'), (3, 'B'), (2, 'C'), (1, 'D'), (0, 'F'), (None, 'NA')], null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='eventevalquestion',
            name='answer_type',
            field=models.CharField(choices=[('grade', 'grade'), ('text', 'text'), ('boolean', 'boolean')], max_length=20),
        ),
        migrations.AlterField(
            model_name='eventlabel',
            name='text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='label',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='worker',
            name='role',
            field=models.CharField(blank=True, choices=[('Interested', 'Interested'), ('Moderator', 'Moderator'), ('Panelist', 'Panelist'), ('Performer', 'Performer'), ('Producer', 'Producer'), ('Staff Lead', 'Staff Lead'), ('Teacher', 'Teacher'), ('Technical Director', 'Technical Director'), ('Volunteer', 'Volunteer'), ('Rejected', 'Rejected'), ('Waitlisted', 'Waitlisted'), ('Pending Volunteer', 'Pending Volunteer')], max_length=50),
        ),
    ]
