# Generated by Django 3.0.8 on 2020-08-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20200422_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordering',
            name='class_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordering',
            name='class_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ordering',
            name='role',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
