# Generated by Django 3.2.16 on 2022-11-14 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20221114_0808'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventContainer',
        ),
    ]
