# Generated by Django 3.0.8 on 2020-08-14 20:37

from django.db import migrations, models


def separate_max(apps, schema_editor):
    Event = apps.get_model('scheduler', 'Event')
    for event in Event.objects.all():
        if event.max_volunteer > 0:
            event.max_commitments = event.max_volunteer
            event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_auto_20200810_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_commitments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(separate_max),
    ]
