# Generated by Django 3.0.8 on 2020-08-16 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_event_max_commitments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActResource',
        ),
    ]
