# Generated by Django 3.0.8 on 2020-08-18 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0016_remove_act_actitem_ptr'),
        ('scheduler', '0010_delete_actresource'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActItem',
        ),
    ]
