# Generated by Django 3.2.18 on 2023-05-15 19:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gbe', '0035_remove_worker_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduler', '0012_move_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='_item',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='resource_ptr',
        ),
        migrations.RemoveField(
            model_name='workeritem',
            name='resourceitem_ptr',
        ),
        migrations.RemoveField(
            model_name='ordering',
            name='allocation',
        ),
        migrations.AlterUniqueTogether(
            name='eventevalboolean',
            unique_together={('user', 'event', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='eventevalcomment',
            unique_together={('user', 'event', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='eventevalgrade',
            unique_together={('user', 'event', 'question')},
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
        migrations.RemoveField(
            model_name='eventevalboolean',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='eventevalcomment',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='eventevalgrade',
            name='profile',
        ),
        migrations.DeleteModel(
            name='WorkerItem',
        ),
    ]
