# Generated by Django 3.2.18 on 2023-05-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_lock_back_down'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='_item',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='resource_ptr',
        ),
        migrations.RemoveField(
            model_name='workeritem',
            name='resourceitem_ptr',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
        migrations.DeleteModel(
            name='WorkerItem',
        ),
    ]
