# Generated by Django 3.2.18 on 2023-09-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_migrate_commitments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordering',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='ordering',
            name='class_name',
        ),
    ]
