# Generated by Django 3.2.18 on 2023-09-10 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0016_auto_20230907_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='peer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_peer', to='scheduler.event'),
        ),
    ]
